version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  commit-message:
      prefix: ":seedling:"
  reviewers:
          - "azeemshaikh38"
          - "naveensrinivasan"
          - "laurentsimon"
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: "daily"
  commit-message:
      prefix: ":seedling:"
  reviewers:
          - "azeemshaikh38"
          - "naveensrinivasan"
          - "laurentsimon"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  commit-message:
      prefix: ":seedling:"
  reviewers:
          - "azeemshaikh38"
          - "naveensrinivasan"
          - "laurentsimon"
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directory: "/gitcache"
  schedule:
    interval: daily
  commit-message:
      prefix: ":seedling:"
  reviewers:
          - "azeemshaikh38"
          - "naveensrinivasan"
          - "laurentsimon"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/gitcache"
  schedule:
    interval: daily
  commit-message:
      prefix: ":seedling:"
  reviewers:
          - "azeemshaikh38"
          - "naveensrinivasan"
          - "laurentsimon"
- package-ecosystem: gomod
  directory: "/scripts"
  schedule:
    interval: daily
  commit-message:
      prefix: ":seedling:"
  reviewers:
          - "azeemshaikh38"
          - "naveensrinivasan"
          - "laurentsimon"
  open-pull-requests-limit: 10
